# Generated by Django 6.0 on 2026-02-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_person_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='todoapp.person')),
            ],
        ),
    ]
