# Generated by Django 6.0 on 2026-02-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todoapp.person'),
            preserve_default=False,
        ),
    ]
