# Generated by Django 6.0 on 2026-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_task_email_task_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
